### ISSUE TITLE
0.3.0 Able to play one-shots but not select Soundsets

### ISSUE THREAD

**Issue by drober76** [frondeus/fvtt-syrin-control#35]
**Describe the bug**
Using module 0.3.0, Foundry v9 on Forge in Chrome on Mac, the Soundset pull-down shows all available soundsets, but when a soundset is selected, the drop down closes and returns to the default "-no soundset-" selection. Moods remain unselectable. 

Global one-shots load in the Ambient Sound browser and can be played, so API key appears to be functioning.

**Details**
 - OS: macOS 12.2
 - Chrome Version 99.0.4844.51 
 - Foundry VTT v9 on Forge
 - Module version: 0.3.0
 - Does not work in safety mode
 - [X] I did read FAQ - https://github.com/frondeus/fvtt-syrin-control/wiki/Frequently-Asked-Questions
-->

**Comment by frondeus** [comment]
Can you select a soundset/mood in the playlist?
Is it only related to scene config?

Anyway: That sounds not right. Definitely. Could you send me what the logs say?

**Comment by DrWiFi** [comment]
Hello,
I am having the same issue. This is in the main sound tab, though the scene ambiance dialog box acts the same.
I tried downloading Firefox and it appears to work as intended, however Chrome behaves as described above.
I can start / stop a previously saved playlist and the global oneshots.
There is no entry in the dev tools when I select the drop down item.

**Comment by frondeus** [comment]
Hi, thanks for extra details. I will look into it soon.

**Comment by decron82** [comment]
I am also seeing this issue running on forge-vtt.com. If I can help please let me know.

**Comment by RyanD** [comment]
I am having same issue.. if its related I am using their subscription package so my soundset options are huge

**Comment by RyanD** [comment]
I am using Foundry app btw

**Comment by frondeus** [comment]
Okay, sorry for the long waiting time.

Lets make a summary of #35, #38 and #42.
It seems to me that there is one bug occurring on Chrome/Chromium/Edge (edge is using chrome engine so it makes sense), and also probably only on macOS.

The problem is, I am unable to replicate the bug, however, I'm using Linux & Windows only.
First of all I am going to close other issues and keep this one only.

**Comment by frondeus** [comment]
When you select a soundset, the SyrinControl sends a request to SyrinscapeAPI asking what moods are part of the set.
While waiting for the response, it blocks mood selection since it might be updated at any second.
Then it seems that the response never arrives, or it's invalid, or there is another nasty bug causing it to enter the invalid state.
Because of that, it never enables the dropdown again. 

That's all that I know. I would have to know what the response was (if there was any response).
I'm sure your API keys are correct since you were able to retrieve a list of soundsets. That's something.
But I'm not sure why, oh why another request is causing problems only on Chrome.

**Comment by frondeus** [comment]
On my Chrome it looks like this:

![Screenshot from 2022-08-08 22-36-16](https://user-images.githubusercontent.com/1165825/183512910-116e5fd4-0a91-4493-83cb-659487ddc098.png)

I am getting response for the request called `?soundset__id=...` and the status is as expected: 200

**Comment by frondeus** [comment]
I released https://github.com/frondeus/fvtt-syrin-control/releases/tag/0.3.1-alpha1-3
Could someone install it manually (not via ForgeVTT and not via Foundry update mechanism, just Drag n Drop into the foundry modules dir) and see if there are more logs? And paste them here :)?

It should look like this:

![Screenshot from 2022-08-09 22-38-00](https://user-images.githubusercontent.com/1165825/183756377-9ab9f17f-9c5d-428f-b64e-622df7bc8f72.png)

**Comment by frondeus** [comment]
This link also should work if you want to install it via Foundry or Forge manager:
https://github.com/frondeus/fvtt-syrin-control/releases/download/0.3.1-alpha1-3/module.json

**Comment by frondeus** [comment]
I just released version 0.3.1 it should fix the issue.
