### ISSUE TITLE
Sound is not playing.

### ISSUE THREAD

**Issue by frondeus** [frondeus/fvtt-syrin-control#94]
Not sure if this is related. But I installed the module and added it to a Starfinder campaign. Selecting sound sets was fine, and they list them but if I play any the drop-down does not and the play button is just the stop button. No progress no time nothing to show it is playing. Which it isn't.

See image. 

![Screenshot from 2023-04-07 14-45-56](https://user-images.githubusercontent.com/7777993/230619375-fe18c36e-8d0f-47f4-9976-ed6fa4d9a5e8.png)

Is it supposed to cache the files before playing them? In which case does it matter how many sound sets you select? 

EDIT: 

FWIW:  I do see a call to syrinscape.com though I don't see any further traffic. This is the response.

```
HTTP/1.1 101 Switching Protocols
Date: Fri, 07 Apr 2023 14:03:15 GMT
Connection: upgrade
Upgrade: websocket
Sec-WebSocket-Accept: +aJ57Ib1HEXPoYiJUSsUcD+F4L8=
CF-Cache-Status: DYNAMIC
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=t6pfMW7yCPyShzGTm%2FIAfbNVfDax5H7hr2uGygVtgiExxdtVFposOjksNrqU%2BRGr0uj8blF4ZsBDEt6r9QAbxl6GS9ZjajzusWfau4BXk305Gkd7RXEh2ysyA4mdV9f23O7H"}],"group":"cf-nel","max_age":604800}
NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
Server: cloudflare
CF-RAY: 7b42d0194aff7767-LHR
```

EDIT 2:

Something did show up, though unsure of it's relevance 

![Screenshot from 2023-04-07 15-13-31](https://user-images.githubusercontent.com/7777993/230623667-a4cac0b6-3628-4017-bd6f-85f5bbd95629.png)

Hmm, dunno why it through that error, but  doesn't seem that important really.

![Screenshot from 2023-04-07 15-19-39](https://user-images.githubusercontent.com/7777993/230624671-dcfa5044-7020-4822-8c4e-90c11d753b97.png)

_Originally posted by @develroo in https://github.com/frondeus/fvtt-syrin-control/issues/87#issuecomment-1500304240_
            
            
Lets continue here because I have an impression you had actually a bug.
First of all - I just released https://github.com/frondeus/fvtt-syrin-control/releases/tag/0.4.3
Could you tell me if that version works better?

**Comment by develroo** [comment]
OK .. now i feel I can contribute because it WORKS!. At least with the syrinscape online window open. I can see it changed the controls in the sidebar and plays, scenes or one-shots. However, it still does not work from the sidebar side. I tried the same sound sets but some reason the icon changes and nothing happens.

So yes, it does work (even on stand-alone servers) but the sidebar controls don't seem to function.

Just to be specific. You can start a mood from the Sysrinscape online window and the icon on the sidebar will change to a stop button. But clicking that will not stop the mood. Neither will clicking the play button on the sidebar.

That I think is the issue I am trying to address. Sorry.

**Comment by develroo** [comment]
> First of all - I just released https://github.com/frondeus/fvtt-syrin-control/releases/tag/0.4.3
Could you tell me if that version works better?

Yes! The sidebar controls work now!!! Thank you so much. So sorry to be such a pain as a new user.

Hope it helps others, though.

Keep up the good work!

**Comment by frondeus** [comment]
Can i close this issue then?

**Comment by develroo** [comment]
> Can i close this issue then?

Sure. Whatever you patched seems to fix it both on Chrome and Firefox browser, so as far as I am concerned it works as intended 

Cheers!
